main: me.ixhbinphoenix.smPl.smEntities.Main
name: smEntities
version: 0.0.1
api-version: 1.18
commands:
  zombie:
    usage: /<command>
    description: Summons a Zombie at your location
depend:
  - smCore