main: me.ixhbinphoenix.smPl.smEntities.Main
name: smEntities
version: 0.0.2
api-version: 1.18
commands:
  spawnentity:
    usage: /<command> <entity id>
    description: Summons a Custom Entity at your location
depend:
  - smCore
