main: me.ixhbinphoenix.smPl.smItems.Main
name: smItems
version: 0.0.2
api-version: 1.18
commands:
  meta:
    usage: /<command> [self|reset]
    description: Gives persistentDataContainer information of the held item
  giveitem:
    usage: /<command> item
    description: Gives a test item
  setitemxp:
    usage: /<command> xp
    description: Sets xp of the held item
depend:
  - smCore