main: me.ixhbinphoenix.smPl.smCore.Main
name: smCore
version: 0.0.2
api-version: 1.18
commands:
  pstats:
    usage: /<command>
    description: gives psdc info for player
  setstat:
    usage: /<command> [hand|player] key value
    description: sets psdc info
  delstat:
    usage: /<command> key
    description: deletes psdc info
  spawnentity:
    usage: /<command> <entity id>
    description: Summons a Custom Entity at your location
  meta:
    usage: /<command>
    description: Gives persistentDataContainer information of the held item
  giveitem:
    usage: /<command> item
    description: Gives a test item
  giveresource:
    usage: /<command> item [amount]
    description: Gives one or multiple items of a resource
  setitemxp:
    usage: /<command> xp
    description: Sets xp of the held item
depend:
  - smChat
permissions:
  smcore.staffchat:
    description: Allows to use /sc
    default: op