main: me.ixhbinphoenix.smPl.smCore.Main
name: smCore
version: 0.0.2
api-version: 1.18
commands:
  ping:
    usage: /<command>
    description: Returns pong!
  pstats:
    usage: /<command>
    description: gives psdc info for player
  setstat:
    usage: /<command> [hand|player] key value
    description: sets psdc info
  delstat:
    usage: /<command> key
    description: deletes psdc info
  sc:
    usage: /<command> message
    permission: smcore.staffchat
    description: Sends a message in staffchat
  toggleping:
    usage: /<command>
    description: Toggles the ping sound
permissions:
  smcore.staffchat:
    description: Allows to use /sc
    default: op